const PRODUCTS_ACTION_TYPES = {
  SET_PRODUCTS_START: "SET_PRODUCTS_START",
  SET_PRODUCTS_SUCCESS: "SET_PRODUCTS_SUCCESS",
  SET_PRODUCTS_FAILED: "SET_PRODUCTS_FAILED",
};

export default PRODUCTS_ACTION_TYPES;
